'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Save, Copy, Loader2, Check } from 'lucide-react'
import { useCreateNote } from '@/lib/hooks/use-notes'
import { toast } from 'sonner'

const IMAGE_GALLERY_PREFIX = '__IMAGE_GALLERY__:'

interface MessageActionsProps {
  content: string
  notebookId?: string
  selectedImageIndex?: number
}

export function MessageActions({ content, notebookId, selectedImageIndex = 0 }: MessageActionsProps) {
  const [copySuccess, setCopySuccess] = useState(false)
  const createNote = useCreateNote()
  const imageDataUrls = extractImageDataUrls(content)
  const isImageMessage = imageDataUrls.length > 0

  const buildNoteContent = () => {
    if (!isImageMessage) return content
    if (imageDataUrls.length === 1) {
      return `![Generated image](${imageDataUrls[0]})`
    }
    return imageDataUrls
      .map((url, idx) => `### Image ${idx + 1}\n\n![Generated image ${idx + 1}](${url})`)
      .join('\n\n')
  }

  const handleSaveToNote = () => {
    if (!notebookId) {
      toast.error('Cannot save note: notebook ID not available')
      return
    }

    createNote.mutate({
      content: buildNoteContent(),
      note_type: 'ai',
      notebook_id: notebookId,
      // Title will be auto-generated by the API for AI notes
    })
  }

  const copyImageToClipboard = async (dataUrl: string) => {
    if (!navigator.clipboard) {
      throw new Error('Clipboard API is not available')
    }
    if (!('ClipboardItem' in window) || !navigator.clipboard.write) {
      throw new Error('Binary clipboard write is not supported in this browser')
    }
    const response = await fetch(dataUrl)
    const blob = await response.blob()
    const item = new ClipboardItem({ [blob.type || 'image/png']: blob })
    await navigator.clipboard.write([item])
  }

  const handleCopyToClipboard = async () => {
    try {
      if (isImageMessage) {
        const safeIndex = Math.min(Math.max(selectedImageIndex, 0), imageDataUrls.length - 1)
        await copyImageToClipboard(imageDataUrls[safeIndex])
        toast.success(
          imageDataUrls.length > 1
            ? `Copied image ${safeIndex + 1} of ${imageDataUrls.length} to clipboard`
            : 'Image copied to clipboard'
        )
        setCopySuccess(true)
        setTimeout(() => setCopySuccess(false), 2000)
        return
      }

      // Try modern clipboard API first
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(content)
        toast.success('Message copied to clipboard')
        setCopySuccess(true)
        setTimeout(() => setCopySuccess(false), 2000)
      } else {
        // Fallback for older browsers
        const textArea = document.createElement('textarea')
        textArea.value = content
        textArea.style.position = 'fixed'
        textArea.style.left = '-999999px'
        textArea.style.top = '-999999px'
        document.body.appendChild(textArea)
        textArea.focus()
        textArea.select()

        try {
          document.execCommand('copy')
          toast.success('Message copied to clipboard')
          setCopySuccess(true)
          setTimeout(() => setCopySuccess(false), 2000)
        } catch {
          toast.error('Failed to copy message')
        }

        document.body.removeChild(textArea)
      }
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
      if (isImageMessage) {
        toast.error('Failed to copy image to clipboard')
      } else {
        toast.error('Failed to copy message')
      }
    }
  }

  return (
    <TooltipProvider>
      <div className="flex gap-1">
        {notebookId && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="h-7 px-2"
                onClick={handleSaveToNote}
                disabled={createNote.isPending}
              >
                {createNote.isPending ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Save className="h-3.5 w-3.5" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent>
            <p>{isImageMessage ? 'Save image(s) to note' : 'Save to note'}</p>
            </TooltipContent>
          </Tooltip>
        )}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2"
              onClick={handleCopyToClipboard}
              disabled={createNote.isPending}
            >
              {copySuccess ? (
                <Check className="h-3.5 w-3.5 text-green-500" />
              ) : (
                <Copy className="h-3.5 w-3.5" />
              )}
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            <p>{isImageMessage ? 'Copy image to clipboard' : 'Copy to clipboard'}</p>
          </TooltipContent>
        </Tooltip>
      </div>
    </TooltipProvider>
  )
}

function extractImageDataUrls(content: string): string[] {
  if (content.startsWith('data:image/')) {
    return [content]
  }
  if (!content.startsWith(IMAGE_GALLERY_PREFIX)) {
    return []
  }
  try {
    const payloadText = content.slice(IMAGE_GALLERY_PREFIX.length)
    const payload = JSON.parse(payloadText)
    const images = Array.isArray(payload?.images) ? payload.images : []
    return images.filter((url): url is string => typeof url === 'string' && url.startsWith('data:image/'))
  } catch {
    return []
  }
}
